# Generated by Django 3.2.9 on 2022-01-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showkase_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
