# Generated by Django 3.2.9 on 2022-01-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showkase_app', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
